version: "3"

services:
  ros:
    build: .
    privileged: true
    tty: true
    network_mode: "host"
    volumes:
      #- /home/hardik/Research/hsr/:/home/hsr
      #- /home/hardik/Desktop/Research/Toyota/hsr/:/home/hsr
      #- /home/hardik/Research/hsr/colcon_ws/:/home/colcon_ws
       - /home/hardik/Desktop/Research/Toyota/hsr/colcon_ws/:/home/colcon_ws
      # - /home/hardik/Desktop/Research/hsr/catkin_ws/src/dependencies/CrowdNav:/home/CrowdNav
    environment:
      - NVIDIA_DISABLE_REQUIRE=1
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

