version: "3"

services:
  ros:
    build: .
    privileged: true
    tty: true
    network_mode: "host"
    volumes:
      - /home/hardik/Research/hsr/code:/home/code
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

